### ISSUE TITLE
Amazon and Netflix 800A03EA Error Cdoe

### ISSUE THREAD

**Issue by Kanekid2m** [Tithen-Firion/UserScripts#11]
Hi,

I am trying since a while to run the amazon script to download some Subtitles but there is something seems to be not right. I downloaded the requirments and tried to run the script but I am getting this Error code all the time and I searched on the internet but it says that there are invailed characters in the code. But I think there is a way to run it and since I am not a big fan of java and dont work with java scripts I dont know how to run it. I am on Windows 10 and I hope you can guide me how to run it without any Problems

**Comment by Tithen-Firion** [comment]
It's a UserScript. You need a UserScript browser add-on, you don't run the `.user.js` file.
