### ISSUE TITLE
Hi . Script itunes Not Working in TV Series 

### ISSUE THREAD

**Issue by MrGamesKingPro** [Tithen-Firion/UserScripts#12]
Hi . Script itunes does not work with TV Series . Is there a solution to it? 
https://tv.apple.com/us/show/the-unexplained-files/umc.cmc.3vfcoblexexupe2mxosbj9sak

**Comment by Tithen-Firion** [comment]
Could you send me a screenshot of any subtitles in that series? Because from the data available for free I can see the info about English closed captions only - and they seem to be muxed with the video so my script won't be able to download them.

**Comment by MrGamesKingPro** [comment]
Do you have any idea to create a script Download Subtitles for Google Play Movies? 
https://play.google.com/store/movies/details/Monster_Hunter?id=mx8nuaKEwZo.P&hl=en&gl=US

**Comment by Tithen-Firion** [comment]
No.
