### ISSUE TITLE
Amazon Script No Longer Works?

### ISSUE THREAD

**Issue by MichaelYochpaz** [Tithen-Firion/UserScripts#16]
Hey, haven't used the script in a while.
I remember there used to be a UI for downloading subtitles when playing a video on Amazon, but now I can't find it anywhere, so I can't download the subtitles...

Could it be that the script is broken after some changes Amazon made or something?

**Comment by Tithen-Firion** [comment]
The only report (on [GreasyFork](https://greasyfork.org/pl/scripts/34885-amazon-video-subtitle-downloader/discussions/109389)) that something is wrong is from December. And they weren't too cooperative. I don't have any account to test/fix it now anyway.

**Comment by MichaelYochpaz** [comment]
Seems like it was my fault for forgetting how to download using this script...
I've started playing a movie and looked for a download-subtitles UI like the Netflix script, but forgot that it's actually on the media's description page and not during playback.

The script seems to work fine, sorry for the hassle and thanks :)
