### ISSUE TITLE
HBO possibillity?

### ISSUE THREAD

**Issue by kralj24** [Tithen-Firion/UserScripts#18]
Hi, thank you for your NF sub download script.

I was wondering is it possible to edit the script to work on hbo?
Subs are also in .vtt format

Thank you, have a nice day. :)

**Comment by Tithen-Firion** [comment]
Not unless someone provides me a HBO account for creating the script and then every time it breaks - for fixing it.

**Comment by kralj24** [comment]
> Not unless someone provides me a HBO account for creating the script and then every time it breaks - for fixing it.

I will give you access to my hbo acc but in private somehow. Can you leave an email or something and then delete it in the edit?

**Comment by Tithen-Firion** [comment]
If you want to contact me privately you can do so on [Greasyfork](https://greasyfork.org/users/15883-tithen-firion).
