### ISSUE TITLE
Netflix Subtitle Downloader

### ISSUE THREAD

**Issue by katzurki** [Tithen-Firion/UserScripts#19]
Hi there!

This is less an issue and more of a way to get in touch with you.

I came across your excellent implementation of the way to download subtitles from Netflix.

Would you be available to provide advice on like functionality for another service? Your time would of course be compensated.

Please let me know if we can talk in more detail. On Telegram would be best—I'm @osfer—but email is also good: katzurki@gmail.com

Please delete this "issue" once you've seen it. Thank you.

Best regards,
Dan

**Comment by Tithen-Firion** [comment]
If you want to contact me privately you can do so on [Greasyfork](https://greasyfork.org/users/15883-tithen-firion).
