### ISSUE TITLE
download arabic subtitles or other language from netflix srt

### ISSUE THREAD

**Issue by hackxing** [Tithen-Firion/UserScripts#2]
we found way that make as download any subtitle srt from netflix with kodi 

https://www.youtube.com/watch?v=LH8q1a7NVtM&feature=youtu.be

so i wanna ask you if you can help as to develop this script or at less to make it easier
that will be grate  
i'm waiting your answer

**Comment by Tithen-Firion** [comment]
I've been trying to make it work whole day. I got all I need to decrypt messages sent from and to server. Decryption throws error. So I've tried another method and got that data. It's compressed with LZW. Decompression throws error. Minified JavaScript code from Netflix gave me headache so I give up for now. Don't expect it to be incorporated into my script soon or even at all.

**Comment by hackxing** [comment]
you should do exactly as the video and maybe because you forgot to change the name of text to AhmedBafkir and put if in c like on the video 08:14

**Comment by Tithen-Firion** [comment]
I know it works. I was trying to incorporate that method in my UserScript.

**Comment by hackxing** [comment]
maybe if you make UserScript for kodi will be easier

**Comment by Tithen-Firion** [comment]
Kodi and its plugins are written in Python. UserScripts are written in JavaScript. I'm not familiar with Kodi, ask somebody else.

**Comment by Tithen-Firion** [comment]
New version of the script supports this.
