### ISSUE TITLE
Steam Trade Matcher Userscript Improvements

### ISSUE THREAD

**Issue by jaredcat** [Tithen-Firion/UserScripts#22]
https://gist.github.com/jaredcat/0a60832095a32332aa051e69c2e90cf4

 * Open multiple trade windows if over 100 tradable items
 * Side-by-side trade window view setting
 * Trade recovery if items are missing

**Comment by Tithen-Firion** [comment]
Wrong repository, [this one](https://github.com/Tithen-Firion/STM-UserScript) is for STM UserScript. But I see that Robou made substantial changes to the script himself, so you should contact him, not me.

**Comment by jaredcat** [comment]
Thanks for the link. Weird, i looked at your repos and didn't see that. I wish STM linked to the repo too
