### ISSUE TITLE
Amazon UK

### ISSUE THREAD

**Issue by ixj68855** [Tithen-Firion/UserScripts#3]
I do not know why
does not work
https://www.amazon.co.uk/gp/video/detail/B078YF54JR/
https://www.amazon.co.uk/The-Sound-of-Rain/dp/B078X3P7BW

And this works
https://www.amazon.co.uk/Contract/dp/B078Z6T59G/
https://www.amazon.co.uk/ONE-SHARPER-FANGS-WILL-WIN/dp/B078YT5TQB

**Comment by Tithen-Firion** [comment]
What do you mean by "does not work"? Is there no download button or nothing happens when you click it? I don't have Amazon Prime anymore so I can't help much. Can you confirm that script actually runs on that page? 
Try this url: https://www.amazon.co.uk/KOKKOKU/dp/B078TK9KWN/

**Comment by ixj68855** [comment]
Sry
>nothing happens when you click it

rofl
by clicking on your link, everything works.

~~
I can give you an acc if this helps.

**Comment by Tithen-Firion** [comment]
PM me on [Greasyfork](https://greasyfork.org/forum/profile/Tithen-Firion) or Discord (`Tithen-Firion#2753`), I'll see what I can do tomorrow.

**Comment by ixj68855** [comment]
Accept the application
A&CVm2#8482 - Discord
