### ISSUE TITLE
Amazon_Video_-_subtitle_downloade

### ISSUE THREAD

**Issue by hackxing** [Tithen-Firion/UserScripts#5]
we can not download any subtitles from movies but it still work with series

**Comment by Tithen-Firion** [comment]
No longer have Amazon Prime so the script will stay as is. Unless someone else fixes it.

**Comment by hackxing** [comment]
I have Amazon Prime account just give me your email to send the account for you

**Comment by Essam315** [comment]
Try to download the subtitles from "primevideo" using Firefox 64 and Tampemonkey (Windows 10), it works fine for me with both movies and TV shows subtitles.
