### ISSUE TITLE
Netflix Subtitle Downloader is giving error in Violentmonkey and Ace Scripts.

### ISSUE THREAD

**Issue by Kravimir** [Tithen-Firion/UserScripts#6]
This is the error message:
`Uncaught (in promise) TypeError: Cannot destructure property `titleP` of 'undefined' or 'null'.
    at _download (<anonymous>:133:33)
    at HTMLLIElement.downloadThis (<anonymous>:152:26)`

It's working with Tampermonkey but not Violentmonkey nor Ace Scripts.

Google Chrome version 71.0.3578.98 (Official Build) (64-bit)
Ace Script v1.1.17
Violentmonkey v2.10.1
Tampermonkey BETA v4.8.5885

**Comment by Tithen-Firion** [comment]
Fixed in 391adea11c814f1cc7e0fc39f7f177b83cc4a3b2
