### ISSUE TITLE
HIDIVE and Crunchyroll

### ISSUE THREAD

**Issue by NewVicious** [Tithen-Firion/UserScripts#7]
Hello and thanks for the script for amazon and netflix, I would also like to ask if you can not do the same for [HIDIVE](https://www.hidive.com/) and [Crunchyroll](https://www.crunchyroll.com/).

Thanks in advance.

**Comment by Tithen-Firion** [comment]
No. From what I see [youtube-dl](https://rg3.github.io/youtube-dl/) supports downloading subs from those already. Use `--skip-download` (this prevents downloading the video) and `--all-subs` (or other option for downloading subs). For example:
```
youtube-dl --skip-download --all-subs https://www.crunchyroll.com/jojos-bizarre-adventure/episode-135-untitled-780774
```
This will download all subs for this episode.

**Comment by NewVicious** [comment]
I know, but I like the method you offer more because it's simpler and without using programs.
