### ISSUE TITLE
Amazon stop work

### ISSUE THREAD

**Issue by MetalDevOps** [Tithen-Firion/UserScripts#8]
Now, i got this error.

![Iprimevideo](https://i.imgur.com/onbnbvC.png)

**Comment by Tithen-Firion** [comment]
What's your browser, add-on, script version, url you got this error on? What exactly did you click on?

**Comment by JustShinobi** [comment]
Nevermid, i just tested again and works,  earlier the link to download the sub was showing up elsewhere and was giving the error quoted.

thanks.

**Comment by kvu64297** [comment]
![](https://puu.sh/DdzTp/4230ba99d9.png)
 ![](https://puu.sh/DdzVk/b7e43d484c.png)
¯\_(ツ)_/¯
