### ISSUE TITLE
Tag <c.bg_transparent> </c.bg_transparent> in some titles

### ISSUE THREAD

**Issue by MetalDevOps** [Tithen-Firion/UserScripts#9]
When i download this sub https://www.netflix.com/watch/80201130 only english sub its ok, others have the tag <c.bg_transparent> </c.bg_transparent> in all lines

1. Portuguese sub

> 1
> 00:00:12.137 --> 00:00:14.097 position:50.00%,middle align:middle size:80.00% line:84.67% 
> <c.bg_transparent>UMA SÉRIE ORIGINAL NETFLIX</c.bg_transparent>
> 
> 2
> 00:00:29.112 --> 00:00:29.946 position:50.00%,middle align:middle size:80.00% line:84.67% 
> <c.bg_transparent>Meliodas!</c.bg_transparent>

2. Italian sub

> 1
> 00:00:12.011 --> 00:00:14.097 position:50.00%,middle align:middle size:80.00% line:84.67% 
> <c.bg_transparent>UNA SERIE ORIGINALE NETFLIX</c.bg_transparent>
> 
> 2
> 00:00:29.112 --> 00:00:29.946 position:50.00%,middle align:middle size:80.00% line:84.67% 
> <c.bg_transparent>Lord Meliodas!</c.bg_transparent>

3. French sub

> 1
> 00:00:12.137 --> 00:00:14.097 position:50.00%,middle align:middle size:80.00% line:84.67% 
> <c.bg_transparent>UNE SÉRIE ORIGINALE NETFLIX</c.bg_transparent>
> 
> 2
> 00:00:29.112 --> 00:00:29.946 position:50.00%,middle align:middle size:80.00% line:84.67% 
> <c.bg_transparent>Messire Méliodas !</c.bg_transparent>

Only english sub its ok, I remember seeing it in another title too, but I can not remember which one, can you check if can fix it?

**Comment by Tithen-Firion** [comment]
Just read the description. https://greasyfork.org/scripts/26654-netflix-subtitle-downloader I'm not going to do anything with it. My script lets you download original, unmodified subs in WebVTT format. And that works perfectly well.
